### ISSUE TITLE
EXC_BAD_ACCESS in layoutCellWithCellInfo

### ISSUE THREAD

**Issue by choomz** [ekohe/EKStreamView#18]
Hello,

First thanks for the great work on this lib.

Actually the lib is working great 90% of the time, but sometimes i get a crash when popping the view. It's crashing here : 
https://github.com/ekohe/EKStreamView/blob/master/EKStreamView.m#L292

The delegate is a zombie object, not nil but dealocated. I tried to fix it by setting the stream view to nil when the controller is popped but nothing work actually.

Note that it's on ios7, so I can't use the viewDidUnload method to free the stream view.

I got the bug when scrolling to bottom and then pressing the back button (with more than 5/6 items, in order to trigger the viewDidScroll delegate).

Let me know if you need more clues about the bug, actually I'm not sure how to fix it.

Thanks !

**Comment by choomz** [comment]
Just did a quick & dirty fix here : 
https://github.com/ekohe/EKStreamView/blob/master/EKStreamView.m#L381

By adding a boolean which is setted to true manually when the view controller is popping. So if it's terminating, it's not going into the layoutCellWithCellInfo.

But there must be a cleaner way :)

**Comment by Xenofex** [comment]
Hello, @choomz ,

`delegate` was already released when the line you mentioned was called. This is totally unexpected: `EKStreamView` lives with its delegate, otherwise it renders nothing. In `UITableView`, there is `delegate` and `datasource`. Here I didn't split that because I want it simpler.

The reason is probably some logic error in your code, where the `delegate` object was released unexpectedly. 90% of the time `delegate` is the view controller, which releases all its views before deallocated. But there is still a chance that the `EKStreamView` has a zombie delegate. In this case, you have to set `delegate` to `nil` when the `delegate` object was released. Apparently you know which the object is and, when it's deallocated. So it should be fine with the current implementation of `EKStreamView`.

However to make it more robust, I can update the `delegate` property from `unsafe_unretained` to `weak`. The difference between the 2 is that a `weak` property is automatically set to nil when the referencing object is released, which guarantees the `delegate` object to be a live object or a `nil`. `unsafe_unretained` property doesn't have this. It's for backward compatibility with iOS 4, which I can safely drop now.

**Comment by Xenofex** [comment]
See ecd7f604fd159093ccb594211681081bb364d437. I bumped to version 1.0.3. You can upgrade and your issue is fixed. However you have to check your logic because that's where the real reason lies in.

**Comment by choomz** [comment]
Indeed, `weak` was the solution. I totally agree with you that it's strange, but on ios7, the delegate was the zombie object for the cell which was reused when the view bounces.

For exemple, number 6 over 10 cells. While popping, the layoutCellWithCellInfo was called with a zombie delegate.

Thanks for the update, it works now.
