### ISSUE TITLE
Support for multiple header size rows

### ISSUE THREAD

**Issue by treacher** [ekohe/EKStreamView#8]
Hi there,

I am currently using EKStreamView in a video playing iPhone application. Currently I have all the videos coming through nicely in a 3 column grid view. The next thing I want to be able to do is display promoted videos at the full width of the screen and at a specific height but still keep the grid view for the smaller cells.

Is this something that is currently supported? If not do you have any advice for me in trying to implement this using EKStreamView?

**Comment by Xenofex** [comment]
Sorry that I haven't checked these for days. So in your case do you want your full width will at the top of the grid view? Or you want it in the middle of it? If it's at the top, the top header can by any view. Just include whatever you what there. In my post I put tons of things in the header view to make the whole view like that the grid view is at the bottom of the list. 

If the promoted ones are in the middle of the grid view, there's no support for this now. It seems to be like #1, the section support. The reason that I'm not good with the sections is that in this stream view, the bottom of the columns can not be aligned. the whole view should be like infinite in my opinion, that's why it's called stream view. So I decided not to consider sections at the very beginning. If you do want the sections, that would be some breaking changes since the index for the post is only an integer. It should be an `NSIndexPath` if there are sections.
